# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_signid', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=25)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_idnumber', models.CharField(max_length=19)),
                ('user_type', models.CharField(default='1', max_length=1)),
                ('user_examiner_time', models.DateField()),
                ('user_examine_statue', models.CharField(default='1', max_length=1)),
                ('user_inblack', models.CharField(default=0, max_length=1)),
                ('user_examiner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
