# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('sex', models.CharField(max_length=2, null=True)),
                ('title', models.CharField(max_length=15, null=True)),
                ('title_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('major', models.CharField(max_length=30, null=True)),
                ('major_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('idnum_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('education', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100, null=True)),
                ('time', models.DateField(null=True)),
                ('type', models.CharField(max_length=1, null=True)),
                ('file', models.FileField(null=True, upload_to='/upload_file/')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('grade', models.CharField(max_length=8, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('contacts', models.CharField(max_length=25, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('setupdate', models.DateField(null=True)),
                ('legalpersoncode', models.CharField(max_length=30, null=True, unique=True)),
                ('legalpersoncode_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('zipcode', models.CharField(max_length=6, null=True)),
                ('superiordepartment', models.CharField(max_length=50, null=True)),
                ('assets', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('qualification', models.CharField(max_length=25, null=True)),
                ('qualification_date', models.DateField(null=True)),
                ('qualification_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('quality', models.CharField(max_length=25, null=True)),
                ('quality_date', models.DateField(null=True)),
                ('quality_file', models.FileField(null=True, upload_to=b'')),
                ('artisan_sum', models.IntegerField(null=True)),
                ('artisan_m_sum', models.IntegerField(null=True)),
                ('artisan_h_sum', models.IntegerField(null=True)),
                ('artisan_e_sum', models.IntegerField(null=True)),
                ('artisan_mj_sum', models.IntegerField(null=True)),
                ('artisan_en_sum', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('fax', models.CharField(max_length=20, null=True)),
                ('request_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('explain_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('lisence_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('system_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('assets_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('equipment_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('place_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('score', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('begintime', models.DateField(null=True)),
                ('endtime', models.DateField(null=True)),
                ('continuetimes', models.IntegerField(null=True)),
                ('examiner_time', models.DateField()),
                ('examine_statue', models.CharField(default='1', max_length=1)),
                ('inblack', models.CharField(default=0, max_length=1)),
                ('changewant', models.CharField(default=0, max_length=1)),
                ('changereason', models.TextField(null=True)),
                ('changewanttime', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('level', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('investment', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('investment_sb', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('assumemethod', models.CharField(max_length=1, null=True)),
                ('time', models.CharField(max_length=50, null=True)),
                ('approval', models.CharField(max_length=100, null=True)),
                ('approval_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='StackHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('sex', models.CharField(max_length=2, null=True)),
                ('title', models.CharField(max_length=15, null=True)),
                ('title_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('major', models.CharField(max_length=30, null=True)),
                ('major_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('idnum_file', models.FileField(null=True, upload_to='/upload_file/')),
                ('post', models.CharField(max_length=30, null=True)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('train_code', models.CharField(max_length=100, null=True)),
                ('resume', models.TextField(null=True)),
                ('types', models.CharField(max_length=1, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connecter', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
