# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20160905_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='type',
            new_name='itype',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='itype',
        ),
    ]
