# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-17 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20160906_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='idnum_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='major_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='title_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='assets_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='equipment_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='examiner_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='explain_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legalpersoncode_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='lisence_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='place_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='qualification_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='request_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='system_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approval_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='stackholder',
            name='idnum_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='stackholder',
            name='major_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='stackholder',
            name='title_file',
            field=models.FileField(null=True, upload_to='upload_file/'),
        ),
    ]
