# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20160917_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='assets_file',
            field=models.FileField(null=True, upload_to='upload_file/assets_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='equipment_file',
            field=models.FileField(null=True, upload_to='upload_file/equipment_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='examine_statue',
            field=models.CharField(default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='explain_file',
            field=models.FileField(null=True, upload_to='upload_file/explain_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legalpersoncode_file',
            field=models.FileField(null=True, upload_to='upload_file/legalpersoncode_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='lisence_file',
            field=models.FileField(null=True, upload_to='upload_file/lisence_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='place_file',
            field=models.FileField(null=True, upload_to='upload_file/place_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='qualification_file',
            field=models.FileField(null=True, upload_to='upload_file/qualification_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='quality_file',
            field=models.FileField(null=True, upload_to='upload_file/quality_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='request_file',
            field=models.FileField(null=True, upload_to='upload_file/request_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='system_file',
            field=models.FileField(null=True, upload_to='upload_file/system_file/'),
        ),
        migrations.AlterField(
            model_name='stackholder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stackholder', to='companies.Company'),
        ),
    ]
