# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20160924_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='idnum',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stackholder',
            name='idnum',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='approval',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
