# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20160924_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisan', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='idnum_file',
            field=models.FileField(null=True, upload_to='upload_file/idnum_file/'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='major_file',
            field=models.FileField(null=True, upload_to='upload_file/major_file/'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='title_file',
            field=models.FileField(null=True, upload_to='upload_file/title_file/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='companies.Artisan'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(null=True, upload_to='upload_file/certificates_file/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approval_file',
            field=models.FileField(null=True, upload_to='upload_file/approval_file/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stackholder',
            name='idnum_file',
            field=models.FileField(null=True, upload_to='upload_file/idnum_file/'),
        ),
        migrations.AlterField(
            model_name='stackholder',
            name='major_file',
            field=models.FileField(null=True, upload_to='upload_file/major_file/'),
        ),
        migrations.AlterField(
            model_name='stackholder',
            name='title_file',
            field=models.FileField(null=True, upload_to='upload_file/title_file/'),
        ),
    ]
