# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20161006_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='onjobe_file',
            field=models.FileField(null=True, upload_to='upload_file/onjobe_file/'),
        ),
        migrations.AddField(
            model_name='company',
            name='itype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stackholder',
            name='work_year',
            field=models.IntegerField(null=True),
        ),
    ]
