# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20161021_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='onjobe_file',
        ),
        migrations.AddField(
            model_name='artisan',
            name='onjob_file',
            field=models.FileField(null=True, upload_to='upload_file/onjob_file/'),
        ),
    ]
