# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-05 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20161021_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='legalpersoncode',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
