# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-05 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20161105_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='creditcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='isgroup',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zipcodeplace',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='build_company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_file',
            field=models.FileField(null=True, upload_to='upload_file/contract_file/'),
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='timebef',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stackholder',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='stackholder',
            name='work_file',
            field=models.FileField(null=True, upload_to='upload_file/work_file/'),
        ),
    ]
