# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20161106_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='jobcerti_file',
            field=models.FileField(null=True, upload_to='upload_file/jobcerti_file/'),
        ),
        migrations.AddField(
            model_name='company',
            name='Company_work_begin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Company_work_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='certi_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='certi_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fingrade',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stackholder',
            name='birhtd',
            field=models.DateField(null=True),
        ),
    ]
