# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20161109_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='assets_file',
        ),
        migrations.RemoveField(
            model_name='company',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='company',
            name='equipment_file',
        ),
        migrations.RemoveField(
            model_name='company',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='company',
            name='legalpersoncode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lisence_file',
        ),
        migrations.RemoveField(
            model_name='company',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='company',
            name='qualification_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='qualification_file',
        ),
        migrations.RemoveField(
            model_name='company',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='company',
            name='quality_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='superiordepartment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='approval_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='assumemethod',
        ),
        migrations.RemoveField(
            model_name='project',
            name='investment_sb',
        ),
        migrations.RemoveField(
            model_name='stackholder',
            name='post',
        ),
        migrations.RemoveField(
            model_name='stackholder',
            name='train_code',
        ),
        migrations.AddField(
            model_name='project',
            name='address_a',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='address_b',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='address_c',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='approval_a_file',
            field=models.FileField(null=True, upload_to='upload_file/approval_a_file/'),
        ),
        migrations.AddField(
            model_name='project',
            name='approval_b_file',
            field=models.FileField(null=True, upload_to='upload_file/approval_b_file/'),
        ),
        migrations.AddField(
            model_name='project',
            name='approval_c_file',
            field=models.FileField(null=True, upload_to='upload_file/approval_c_file/'),
        ),
    ]
