# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20161111_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stackholder',
            old_name='birhtd',
            new_name='birthd',
        ),
        migrations.AddField(
            model_name='artisan',
            name='birthd',
            field=models.DateField(null=True),
        ),
    ]
