# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_auto_20161112_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='three_check',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
