# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_company_three_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='titlemajor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stackholder',
            name='titlemajor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='title',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='stackholder',
            name='title',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
