# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_auto_20161115_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='idnum_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/idnum_file/'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='jobcerti_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/jobcerti_file/'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='major_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/major_file/'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='onjob_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/onjob_file/'),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='title_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/title_file/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(null=True, upload_to='assets/upload_file/certificates_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='explain_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/explain_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legalpersoncode_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/legalpersoncode_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='place_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/place_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='quality_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/quality_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='request_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/request_file/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='system_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/system_file/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approval_a_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/approval_a_file/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approval_b_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/approval_b_file/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approval_c_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/approval_c_file/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/contract_file/'),
        ),
        migrations.AlterField(
            model_name='stackholder',
            name='idnum_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/idnum_file/'),
        ),
        migrations.AlterField(
            model_name='stackholder',
            name='major_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/major_file/'),
        ),
        migrations.AlterField(
            model_name='stackholder',
            name='title_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/title_file/'),
        ),
        migrations.AlterField(
            model_name='stackholder',
            name='work_file',
            field=models.FileField(null=True, upload_to='assets/upload_file/work_file/'),
        ),
    ]
